### ISSUE TITLE
为什么截出来的图片，页面上带彩色内容消失了？

### ISSUE THREAD

**Issue by xkungxfu** [zkeq/Python-WebSite-Screenshot#3]
full_page采用模式3的时候。页面上带彩色的内容消失了。

**Comment by zkeq** [comment]
如何复现?

**Comment by xkungxfu** [comment]
full_page采用模式3

**Comment by zkeq** [comment]
这张就是模式3啊 哪有?
https://github.com/zkeq/Python-WebSite-Screenshot/blob/master/save/adobe.onmicrosoft.cn/3d279d159b61354062c2fc8aff5295dd.png

**Comment by xkungxfu** [comment]
奇怪了。不知道为什么现在又正常了。
等我再发现问题再反馈。谢谢。我采的是言选。
